### ISSUE TITLE
Add step to cancel PR deploy workflows 

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure-Samples/workshop-migrate-jboss-on-app-service#45]
Investigate adding this to the `clean-up-pr.yaml` workflow:

```
    - name: Cancel the PR deploy workflow
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        workflow_id: 'deploy-pull-requests.yaml'
        access_token: ${{ github.token }}
```

IF someone pushes a commit on a PR then quickly merges it, the workflow to create a slot will be running at the same time the workflow is that **deletes** the slot. Ideally we want to prevent this race condition, perhaps by stopping that other workflow with this action
